MenuScreen:
    name: 'menu'

    music_filename: 'resources/music/Robin Cools - Tetris.ogg'

    canvas:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            size: self.size
            source: 'resources/images/menu_background.png'

    GridLayout:
        cols: 1
        row_default_height: 50
        row_force_default: True
        spacing: 25
        size_hint: 0.3, .5
        pos_hint: {'center_x': .80, 'center_y': .5}

        OSButton:
            text: 'Classic mode'
            on_release:
                root.manager.transition.direction = 'left'
                root.manager.current = 'classic'

        OSButton:
            text: 'Puzzle mode'

        OSButton:
            text: 'Multiplayer'

        OSButton
            text: 'Options'

        OSButton:
            text: 'Quit game'
            on_release:
                app.stop()